name: Deploy Website to cPanel
on:
  push:
    branches:
      - salistack
      - main
jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Fast Deploy Core Files
      run: |
        curl --ftp-create-dirs -T index.php ftp://dhanvisultratek.com/public_html/ -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
        curl --ftp-create-dirs -T about.php ftp://dhanvisultratek.com/public_html/ -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
        curl --ftp-create-dirs -T contact.php ftp://dhanvisultratek.com/public_html/ -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
        curl --ftp-create-dirs -T services.php ftp://dhanvisultratek.com/public_html/ -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
        curl --ftp-create-dirs -T css/style.css ftp://dhanvisultratek.com/public_html/css/ -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
        curl --ftp-create-dirs -T js/init.js ftp://dhanvisultratek.com/public_html/js/ -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
        curl --ftp-create-dirs -T .htaccess ftp://dhanvisultratek.com/public_html/ -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}
