name: Deploy Website to cPanel
on:
  push:
    branches:
      - salistack
      - main
jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Deploy to cPanel
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: dhanvisultratek.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: ./
        remote_dir: /public_html
        delete: false
